var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "              o      o    o                                                     ",
   "              x     xxx   x                                                     ",
   "                          x       oooo                 o o o                    ",
   "                          x     i                 xx                            ",
   "                                                  xxxxxxxxxxxxxx            xx  ",
   "  xx                                                                         x  ",
   "  x                 xxxxx                x o x                               x  ",
   "  x              xxxx                    xxxxx                               x  ",
   "  x          xxxxx                                                           x  ",
   "  x  @                                                           xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                     x    x                                     ",
   "                                     x!!!!x                                     ",
   "                                     x!!!!x                                     ",
   "                                     xxxxxx                                     ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                             x!x  ",
   "                                                                                                           o x!x  ",
   "                       o                                                                                xxxxx!!x  ",
   "                      xxx!!!!!!!!!!xx                                              x o    o x     i     xxxxxxxx  ",
   "                        xxxxxxxxxxxxx        =                                     xxxxxxxxxx           xxxxxxxx  ",
   "                                                                                 xxx                    xxxxxxxx  ",
   "                                                                                                        xxxxxxxx  ",
   "                                 x           i          x                                               xxxxxxxx  ",
   "                                                                                o                       xxxxxxxx  ",
   "                                     oo             oo                          x                       xxxxxxxx  ",
   "                                     xx             xx                                                  xxxxxxxx  ",
   "                                                    xx                          u                       xxxxxxxx  ",
   "                        o                                                                               xxxxxxxx  ",
   "                      xxxxxx                    x                               o                       xxxxxxxx  ",
   "                           x                                                    x                       xxxxxxxx  ",
   "                           x     u                  oo                                                  xxxxxxxx  ",
   "                                                    xx                                                  xxxxxxxx  ",
   "                                         x                                                              xxxxxxxx  ",
   "x                                                                               o                       xxxxxxxx  ",
   "x                                                                               x                       xxxxxxxx  ",
   "x   @                  x i                                  x                                           xxxxxxxx  ",
   "xxxxxxxxxxxxxx!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!  ",
   "xxxxxxxxxxxxxx!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx           xx!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!  ",
   "                      xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx           xx!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!  ",
   "                      xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx           xx!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!  ",
   "                      xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx           xx!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                         xxx  ",
   "                                                                                                         xxx  ",
   "                                                                                                         xxx  ",
   "                                                                                                         xxx  ",
   "                                                                                                         xxx  ",
   "                                                        o            o                                   xxx  ",
   "                                                     xxxxxx        xxxxxx                                xxx  ",
   "                                                         xx!      !xx                                    xxx  ",
   "                                                         xx!      !xx                         o  o  o   xxxx  ",
   "                                                         xx!      !xx                     xxxxxxxxxxxxxxxxxx  ",
   "                                       o                 xx!      !xx                               xxxxxxxx  ",
   "                                x      x      x          xx!    xxxxx                                 xxxxxx  ",
   "                                !!!!!!!!!!!!!!!          xx!      !xx                                 xxxxxx  ",
   "                                xxxxxxxxxxxxxxx          xx!=     !xx                i                 xxxxx  ",
   "                                                         xx!      !xx                                    xxx  ",
   "                                                         xx  o    !xx         o                          xxx  ",
   "                      u                                  xxxxxx   !xx       xxxxxx                       xxx  ",
   "            o                                            xx!      !xx                                    xxx  ",
   "            yyi                                          xx!      !xx                                    xxx  ",
   "                                                         xx!     =!xx                                    xxx  ",
   "                        o                                xx!      !xx                    o                xx  ",
   "                       yy                                xx!      !xx           xx!!!!!!xx                xx  ",
   "                                                         xx!    xxxxx           xxxxxxxxxx                xx  ",
   "                                                         xx!                                              xx  ",
   "                yy                                       xx!      o  o                         xxx        xx  ",
   "                                                         xx!    xxxxxxxxx                                 xx  ",
   "         @                                              xxxx                                           o  xx  ",
   "  !!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx  ",
   "  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "                                                                                                              "]
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
